name: Build and Deploy API to Azure

# Controls when the action will run.
on:
  push:
    branches:
      - develop

# workflow of the pipeline    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.vars.outputs.short_sha }}
    steps:
      - name: Checkout repository
        id: github
        uses: actions/checkout@v3
        
      - name: Setup WebApi .NET on VM
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'
          
      - name: Configure Azure ACR
        uses: azure/docker-login@v2
        with:
          login-server: ${{ vars.ACR_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Set SHA Output
        id: set_sha
        run: echo "sha=$(echo ${{ github.sha }} )" >> $GITHUB_OUTPUT
      - name: Use SHA Output
        run: echo "The commit SHA is ${{ steps.set_sha.outputs.sha }}"
      - name: Get Project Name from Directory
        id: project_name
        run: |
            PROJECT_NAME=$(basename $PWD)
            echo "project_name=$PROJECT_NAME" >> $GITHUB_OUTPUT
      - name: Print Project Name
        run: echo "The project name is ${{ steps.project_name.outputs.project_name }}"
      - name: Build and push Docker image to ACR
        env:
          IMAGE_NAME: ${{ vars.ACR_SERVER }}
          TAG_NAME: ${{ steps.vars.outputs.short_sha }}
          PROJECT_NAME: ${{ steps.project_name.outputs.project_name }}
        run: |
          docker build -f GardenManagement.Dockerfile  -t $IMAGE_NAME/$PROJECT_NAME:latest -t $IMAGE_NAME/$PROJECT_NAME:$TAG_NAME  .
          docker push $IMAGE_NAME/$PROJECT_NAME --all-tags
